from .builds import GemBuildsController
from .gear import GearBuildsController
from .config import ConfigController
from .extractor import ExtractorController
from .gem import GemController
from .gems import GemSetController
from .home import HomeController
from .login import LoginController
from .magic_find import MagicFindController
from .mastery import MasteryController
from .modders import ModdersController
from .mods import ModsController
from .star import StarChartController
from .max_stats import MaxStatsController
from .admin import AdminController
from .health_optimizer import HealthOptimizerController
